otc:
  obs:
    bucket-name: local
local:
  file-storage: .local-storage
error:
  nodes:
    active: true
spring:
  session:
    store-type: redis
  data:
    redis:
      host: localhost
      password: password
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${OAUTH2_CLIENT_ISSUER:}
        registration:
          keycloak:
            client-id: ${OAUTH2_CLIENT_ID:}
            client-secret: ${OAUTH2_CLIENT_SECRET:}
